system:
  name: cyclobutadiene
  training:
    collection_type: static
    config:
      state:
        - ground
        - transition

  validation:
    collection_type: static
    total_samples: 1000000
    config:
      state:
        - ground
        - transition

comparison_idx: 0
