system:
  name: diatomic
  training:
    collection_type: dynamic
    n_configs: 16
    config:
      symbol1: N
      symbol2: N
      R:
        lower: 1.4
        upper: 6.5
        std: 0.05

  validation:
    collection_type: static
    n_configs: 16
    total_samples: 1000000
    config:
      symbol1: N
      symbol2: N
      R: 
        - 1.60151
        - 1.70828
        - 1.81505
        - 1.92181
        - 2.02858
        - 2.13535
        - 2.24212
        - 2.34889
        - 2.45565
        - 2.56242
        - 2.66919
        - 2.77595
        - 2.88272
        - 2.98949
        - 3.09626
        - 3.20302
        - 3.30979
        - 3.41656
        - 3.52333
        - 3.63009
        - 3.73686
        - 3.84363
        - 3.95040
        - 4.05716
        - 4.16393
        - 4.27070
        - 4.37747
        - 4.48423
        - 4.59100
        - 4.69777
        - 4.80454
        - 4.91130
        - 5.01807
        - 5.12484
        - 5.23161
        - 5.33837
        - 5.87221
        - 6.40605