sampling:
  init_width: 0.02
  steps: 40

optimization:
  optimizer_args:
    lr:
      init: 1.e-1
      decay: 1.0
      delay: 1000.0
    transformations:
      - ['clip_by_global_norm', [1.0], {}]
  clip_local_energy: 5.0
  clip_stat: median
  cg:
    linearize: True
    damping:
      method: std_based
      init: 1.e-3
      schedule:
        delay: 1000.0
        decay: 1.0
        min: 1.e-5
        schedule: hyperbola
      std_based:
        base: 1.e-4
        decay: 0.999
    maxiter: 100


surrogate_optimization:
  optimizer_args:
    lr:
      init: 1.e-4
      delay: 5000.0
      decay: 1.0
    transformations:
      - ['scale_by_adam', [], {}]
      - ['add_decayed_weights', [], {}]
  n_steps: 5
  loss_decay: 0.999
  ema_decay_min: 0.99
  ema_decay_max: 0.9999
  threshold: 1.05
  loss: rmse

training:
  batch_size: 4096
  val_batch_size: 8192
  thermalizing_steps: 500
  checkpoint_every: 5000
  max_steps: 60000
  patience: 10000
  ema: 0.99
  eps: 0.001

pretraining:
  steps: 10000
  single: False
  start_from_last: False
  method: ['rhf']
  align_mo: True
  distinct_orbitals: False

log_every: 10
transform_coordinates: True
log_energies: False


evaluation:
  total_samples: 1_000_000
  init_therm_steps: 10_000
  therm_steps: 2_000
