pesnet:
    gnn_params:
        layers: [[32, 64], [32, 64]]
        embedding_dim: 64
        out_mlp_depth: 2
        msg_mlp_depth: 2
        update_mlp_depth: 2
        pos_encoding_config:
            cutoff: 5.
            n_sph: 7
            n_rad: 6
        activation: tanh
        aggregate_before_out: True
    
    dimenet_params:
        emb_size: 128
        out_emb_size: 256
        int_emb_size:  64
        basis_emb_size: 8
        num_blocks: 4

        directional: True
        concat_before_out: True

        num_spherical: 7
        num_radial: 6
        num_rbf: 32
        cutoff: 10
        envelope_exponent: 1
        envelope_type: none

        num_before_skip: 1
        num_after_skip: 2
        num_dense_output: 3

        activation: silu

    ferminet_params:
        determinants: 16
        full_det: True
        hidden_dims: [[256, 32], [256, 32], [256, 32], [256, 32]]
        absolute_spins: False
        update_pair_independent: False
        input_config:
            nuclei_embedding: 64
            out_dim: 64
            mlp_depth: 2
            activation: tanh
            mlp_activation: silu
        activation: silu
        jastrow_config:
            n_layers: 3
            activation: silu

    global_filter: >
        {
            'params': {
                **{
                    '$$$' + '$'*i: [
                        {
                            f'fermi_layers_{i}': {
                                f'Dense_{i}': {
                                    'bias': None
                                }
                                for i in range(3)
                            }
                        }
                    ]
                    for i in range(4)
                },
                'to_orbitals': {
                    'Dense_0': {'bias': None},
                    'Dense_1': {'bias': None},
                },
                '$': [
                    {
                        'input_construction': {
                            'Dense_0': {
                                'bias': None
                            },
                            **{
                                f'MLP_{i}': {
                                    f'Dense_{j}': {'bias': None }
                                    for j in range(2)
                                }
                                for i in range(2)
                            }
                        }
                    }
                ],
                'logsumdet': {
                    'w': None
                },
                '$$': [
                    {
                        'jastrow_up': {
                            f'Dense_{i}': {'bias': None}
                            for i in range(3)
                        },
                        'jastrow_down': {
                            f'Dense_{i}': {'bias': None}
                            for i in range(3)
                        }
                    }
                ],
                '$$$': [
                    {
                        'jastrow_up': {'Dense_2': {'kernel': None}},
                        'jastrow_down': {'Dense_2': {'kernel': None}}
                    }
                ]
            }
        }
    include_default_filter: True
    meta_model: gnn

init_method: default

surrogate:
    emb_size: 128
    out_emb_size: 256
    int_emb_size:  64
    basis_emb_size: 8
    num_blocks: 4
    
    directional: False
    concat_before_out: False

    num_spherical: 7
    num_radial: 6
    num_rbf: 6
    cutoff: 10
    envelope_exponent: 1
    envelope_type: none

    num_before_skip: 1
    num_after_skip: 2
    num_dense_output: 3

    activation: silu
